version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      deps:
        patterns:
          - '*'

  - package-ecosystem: composer
    directories:
      - /
      - /tools/bc-check
      - /tools/cs-fixer
      - /tools/phpstan
    schedule:
      interval: monthly
    groups:
      deps:
        patterns:
          - '*'
