version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    cooldown:
      default-days: 7
    groups:
      deps:
        patterns:
          - '*'
        update-types:
          - minor
          - patch

  - package-ecosystem: composer
    directories:
      - /
      - /tools/bc-check
      - /tools/cs-fixer
      - /tools/phpstan
      - /tools/rector
    schedule:
      interval: monthly
    cooldown:
      default-days: 7
    groups:
      deps:
        patterns:
          - '*'
        update-types:
          - minor
          - patch
