sudo: false

language: php

cache:
  directories:
  - $HOME/.composer/cache/files

env:
  global:
    - CODE_COVERAGE=0
    - STATIC_ANALYSER=0

matrix:
  include:
    - php: '7.3'
      env: LARAVEL='5.8.*' CODE_COVERAGE=1 STATIC_ANALYSER=1

before_script:
  - phpenv config-rm xdebug.ini || true

install:
  - composer require "illuminate/support:${LARAVEL}" --no-interaction --no-update
  - composer install --prefer-dist --no-interaction --no-suggest
  - if [[ $LARAVEL = '5.5.*' ]]; then composer require --dev orchestra/database:3.5 --prefer-dist --no-interaction --no-suggest; fi

script:
  - if [[ $STATIC_ANALYSER = 1 ]]; then sed -e "s#'src'#'src/Rebing'#" -i vendor/nunomaduro/larastan/src/ApplicationResolver.php; composer phpstan; fi
  - if [[ $CODE_COVERAGE = 0 ]]; then vendor/bin/phpunit --colors=always --verbose; fi
  - if [[ $CODE_COVERAGE = 1 ]]; then phpdbg -qrr vendor/bin/phpunit --colors=always --verbose --coverage-clover=coverage.xml; fi

after_success:
 - if [[ $CODE_COVERAGE = 1 ]]; then bash <(curl -s https://codecov.io/bash); fi
