FROM php:8.0.8-cli-alpine

COPY --from=mlocati/php-extension-installer:1.2.45 /usr/bin/install-php-extensions /usr/local/bin/

RUN install-php-extensions \
      xdebug && \
      rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

COPY --from=composer:2.1.3 /usr/bin/composer /usr/local/bin/

COPY ./ /app

WORKDIR /app
